import type { Metadata } from 'next';
import cn from 'classnames';
import Link from 'next/link'

import "./globals.css";
import s from './layout.module.scss';
import { badScriptFont } from '@/fonts/loclaFonts';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={s.root}>
          <div className={cn(s.links, badScriptFont.className)}>
            <Link className={s.link} href="#part1">Обо мне</Link>
            <Link className={s.link} href="#part2">Чем могу помочь</Link>
            <Link className={s.link} href="#part3">Записаться</Link>
          </div>
        </div>
        <div className={s.container}>
          {children}
        </div>
      </body>
    </html>
  );
}
