import type { Metadata } from 'next';
import cn from 'classnames';
import Link from 'next/link'

import "./globals.css";
import s from './layout.module.scss';
import { badScriptFont } from '@/fonts/loclaFonts';
import {Phone} from "lucide-react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className={s.root}>
        <Link
          href="tel:+79827141518"
          target="_blank"
          className={s.link}
        >
          <Phone />
          <div className={s.linkText}>+7-982-714-15-18</div>
        </Link>
      </div>
        <div className={s.container}>
          {children}
        </div>
      </body>
    </html>
  );
}
